# Generated by Django 3.2.16 on 2022-12-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='science',
            new_name='sciencee',
        ),
    ]
