# Generated by Django 3.2.16 on 2022-12-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='ro',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
