# Generated by Django 3.2.16 on 2022-12-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mark_ro'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=90, null=True)),
                ('semester', models.CharField(max_length=90, null=True)),
                ('subj1', models.CharField(max_length=90, null=True)),
                ('subj2', models.CharField(max_length=90, null=True)),
                ('subj3', models.CharField(max_length=90, null=True)),
                ('subj4', models.CharField(max_length=90, null=True)),
                ('subj5', models.CharField(max_length=90, null=True)),
                ('subj6', models.CharField(max_length=90, null=True)),
                ('subj7', models.CharField(max_length=90, null=True)),
                ('subj8', models.CharField(max_length=90, null=True)),
                ('subj9', models.CharField(max_length=90, null=True)),
                ('subj10', models.CharField(max_length=90, null=True)),
                ('time1', models.CharField(max_length=90, null=True)),
                ('time2', models.CharField(max_length=90, null=True)),
                ('time3', models.CharField(max_length=90, null=True)),
                ('time4', models.CharField(max_length=90, null=True)),
                ('time5', models.CharField(max_length=90, null=True)),
                ('time6', models.CharField(max_length=90, null=True)),
                ('time7', models.CharField(max_length=90, null=True)),
                ('time8', models.CharField(max_length=90, null=True)),
                ('time9', models.CharField(max_length=90, null=True)),
                ('time10', models.CharField(max_length=90, null=True)),
                ('dates', models.DateField()),
            ],
        ),
    ]
