# Generated by Django 3.2.16 on 2023-01-01 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_timetable_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.DateField()),
                ('expiredate', models.DateField()),
                ('pay', models.IntegerField()),
                ('paymentmethod', models.CharField(max_length=90, null=True)),
                ('cardno', models.IntegerField()),
                ('cardname', models.CharField(max_length=90, null=True)),
                ('date', models.CharField(max_length=90, null=True)),
                ('month', models.CharField(max_length=90, null=True)),
                ('cvv', models.CharField(max_length=90, null=True)),
                ('fe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
    ]
