# Generated by Django 3.2.16 on 2023-01-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230101_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fepayment',
            name='cardname',
        ),
        migrations.RemoveField(
            model_name='fepayment',
            name='cardno',
        ),
        migrations.RemoveField(
            model_name='fepayment',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='fepayment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fepayment',
            name='month',
        ),
        migrations.RemoveField(
            model_name='fepayment',
            name='paymentmethod',
        ),
    ]
