# Generated by Django 3.2.16 on 2023-01-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230101_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='fepayment',
            name='enl',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
