# Generated by Django 3.2.16 on 2023-01-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_feepay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepay',
            name='penaltyfee',
        ),
    ]
