# Generated by Django 3.2.16 on 2023-01-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_feepay_penaltyfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fepayment',
            name='upiid',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
