# Generated by Django 3.2.16 on 2023-01-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_feepays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepays',
            old_name='stenrollm',
            new_name='filetype',
        ),
        migrations.RenameField(
            model_name='feepays',
            old_name='transplate',
            new_name='notesfile',
        ),
        migrations.AddField(
            model_name='feepays',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feepays',
            name='subject',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
