# Generated by Django 3.2.16 on 2023-01-09 09:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_auto_20230109_1445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feepays',
            new_name='Notes',
        ),
    ]
