# Generated by Django 3.2.16 on 2023-01-21 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_fepayment_adm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='filetype',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='subject',
        ),
        migrations.AddField(
            model_name='notes',
            name='adharcard',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notes',
            name='cit',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='cona',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='cotac',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='datob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='em',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='fathnam',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='fnamee',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='fulad',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='gen',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='lasnam',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='marksheet',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notes',
            name='mathnamee',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='mgc',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notes',
            name='pc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='regi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
        migrations.AddField(
            model_name='notes',
            name='regist',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='transc',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stufe', models.IntegerField(null=True)),
                ('upiid', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
